### ISSUE TITLE
Support merging errors

### ISSUE THREAD

**Issue by danilokleber** [cowbell/active_model-errors_details#10]
Hey there. Thanks for this backport. It's been really helpful in the legacy project I work on.

Sorry for opening an issue as the project seems to be quite stable. I actually wanted to know if it is possible to backport the method `merge!` from `ActiveModel::Errors` for merging two instances of errors. We can see more information here: https://api.rubyonrails.org/v5.2.3/classes/ActiveModel/Errors.html#method-i-merge-21. I guess it was introduced in `5.2.3`.

Thanks for the time.

**Comment by morgoth** [comment]
Since this gem was meant to be the intermediate step until Rails 5 is released, I would rather not introduce any more features that were implemented later on in Rails.
