### ISSUE TITLE
#set not working correctly

### ISSUE THREAD

**Issue by namxam** [cowbell/active_model-errors_details#3]
ActiveModel also supports a `#set` method to set multiple errors at once:

```
# File activemodel/lib/active_model/errors.rb, line 117
def set(key, value)
  messages[key] = value
end
```

This gem should also override this method, so it sets error details as well.

**Comment by morgoth** [comment]
This method will be deprecated in 5.0 and removed in 5.1, so it won't change error details
https://github.com/rails/rails/blob/c66335d5bb6e5b3d2f6dc42a192e803c7ded5f1c/activemodel/lib/active_model/errors.rb#L128-L136
